# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: ente-cli-$(latest_version)-linux-amd64.tar.gz
artifact_type: tar.gz
binary_name: ente
github_org: ente-io
github_repo: ente
