#!/usr/bin/env bash
set -Eeuo pipefail

filter_out_empty_lines() {
    while IFS= read -r line || [ -n "${line}" ]
    do
        [[ "${line}" =~ ^[[:space:]]*$ ]] || echo "${line}"
    done
}

grep_run_id() {
    grep --perl-regexp '(?<=\s)\d+$' --only-matching
}

# shellcheck disable=SC2016
select_run() {

    template=$(cat <<EOF
{{range .}}
    {{tablerow (timeago .startedAt) (.displayTitle | autocolor "green") (.databaseId)}}
{{end}}
EOF
)

    preview_cmd=$(cat <<EOF
$(declare -f grep_run_id)
run_id="\$(echo {} | grep_run_id)"
gh run view "\${run_id}" 2>&1 | bat --wrap auto --terminal-width "\${FZF_PREVIEW_COLUMNS}"
EOF
)

    export GH_PROMPT_DISABLED=1
    export CLICOLOR_FORCE=1
    gh run list --json name,displayTitle,startedAt,databaseId --template "${template}" \
        | filter_out_empty_lines \
        | SHELL="sh" fzf --ansi --preview "${preview_cmd}" --preview-window "right,40%" \
        | grep_run_id
}

main() {
    run_id="$(
        select_run
    )"

    if gh run watch "${run_id?}"; then
        notify-send "GH Actions run finished!"
    fi
}

main
