#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"
require_commands apt-get

# Thanks to:
#
#    https://stackoverflow.com/a/42265926
#
# and
#
#    https://docs.docker.com/engine/install/ubuntu/#uninstall-docker-engine
#

packages=(
    docker-ce
    docker-ce-cli
    containerd.io
    docker-buildx-plugin
    docker-compose-plugin
    docker-ce-rootless-extras
)

as_root apt-get purge "${packages[@]}"
as_root apt-get autoremove --purge
as_root rm -rf /var/lib/docker
as_root rm -rf /var/lib/containerd
as_root rm -rf /usr/local/lib/docker
