# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: Linux64.zip
artifact_type: zip
binary_name: vt
github_org: VirusTotal
github_repo: vt-cli
