#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands gunzip

GITHUB_ORG="tamasfe"
GITHUB_REPO="taplo"
BIN_NAME="taplo"
UNCOMPRESSED_EXE_NAME="taplo-full-linux-x86_64"

latest_version() {
    echo "${GITHUB_LATEST_TAG}"
}

installed_version() {
    if ! command_exists "${BIN_NAME}"; then
        echo ""
        return 0
    fi

    if ! [[ "$("${BIN_NAME}" --version)" =~ ^taplo\ ([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+) ]]; then
        panic "Unable to determine currently installed version!"
        exit 1  # redundant, but useful to shellcheck
    fi

    echo "${BASH_REMATCH[1]}"
}

artifact_name() {
    echo "${UNCOMPRESSED_EXE_NAME}.gz"
}

download_url() {
    echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
    gunzip "${ARTIFACT_PATH}"
    chmod +x "${UNCOMPRESSED_EXE_NAME}"
    mv "${UNCOMPRESSED_EXE_NAME}" "${BIN_NAME}"
    install_user_bin "${BIN_NAME}"
}

install_from_github
install_success
