#!/usr/bin/env bash
set -Eeuo pipefail

# get TOTP codes from your yubikey with an interactive fuzzy search UI
#
# usage:
#
#     fztotp [query]
#
# ex: display interactive fuzzy search UI
#
#     fztotp
#
# ex: get a specific code without a UI (assuming "github" can identify exactly 1 entry)
#
#     fztotp github
#
# dependencies:
#
# * `fzf`
# * `ykman` (https://docs.yubico.com/software/yubikey/tools/ykman/intro.html)
#    * tip: install via pipx
# * optional: `xsel` to copy to clipboard
#

initial_query="${*}"

panic() {
    echo "${@}" >&2
    exit 1
}

select_code() {
    # prompt the user to select a code (if necessary) and write it to stdout

    codes="$(ykman oath accounts code)" || exit 1
    test "${codes}" != "" || panic "No TOTP codes found on key."
    echo "${codes}" \
        | fzf --height 10 --reverse --select-1 --query "${initial_query}" \
        | awk '{print $2}'
}

code="$(select_code)"

# don't require xsel, but use it if you have it.
if command -v xsel &> /dev/null; then
    echo -n "${code}" | xsel --clipboard
fi

echo "${code}"
