#!/usr/bin/env bash
#
# Push your current local branch to a remote
#
# If you have more than one remote, will prompt you to select which one.
#
set -Eeuo pipefail

main() {
  selected_remote="$(git remote | fzf --select-1 --height 7 --layout reverse)"
  current_branch="$(git rev-parse --abbrev-ref HEAD)"
  git push --set-upstream "${selected_remote}" "${current_branch}"
}

main
