#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

sources_dir="/etc/apt/sources.list.d"
keys_dir="/etc/apt/keyrings"

as_root apt-get remove --yes "nushell"
as_root rm -f "${keys_dir}/fury-nushell.gpg" "${sources_dir}/fury-nushell.list"
