#!/usr/bin/env bash
set -Eeuo pipefail

# Search TUI for man pages
#
# Usage: fzman [QUERY]
#
# Example usage:
#
#     fzman environment.d
#
# Dependencies:
#
# * fzf
#

CLI_ARGS=("$@")

main() {
    INITIAL_QUERY="${CLI_ARGS[*]}"
    FZF_DEFAULT_COMMAND="man -k $(printf %q "${INITIAL_QUERY}")" \
    SHELL=sh \
    fzf --ansi \
        --disabled \
        --query "${INITIAL_QUERY}" \
        --bind "change:reload(man -k {q} || true;)" \
        --preview "man {1}{2}" \
        --bind "enter:become(man {1}{2})"
}

main
