# yaml-language-server: $schema=https://raw.githubusercontent.com/google/yamlfmt/refs/heads/main/schema.json

formatter:
  type: basic
  retain_line_breaks: true
  pad_line_comments: 2
include:
  - .
