# yaml-language-server: $schema=https://www.schemastore.org/github-action.json

name: 'YOLO'
description: "Run <https://philcrockett.com/yolo/v2.sh> with a list of package names"
inputs:
  packages:
    description: 'Space-delimited package names'
    required: true
runs:
  using: "composite"
  steps:

    # TODO: setup github actions caching for downloaded artifacts. adjust `mktemp_dir`
    #       to go to a cacheable location. also centralize temp dir cleanup so we can
    #       clean up temp dirs under normal operations, and cache them in GHA.

    - name: 'Run YOLO script'
      shell: bash
      env:
        PACKAGES: ${{ inputs.packages }}
      run: |
        curl -SsfL https://philcrockett.com/yolo/v2.sh \
            | bash -s -- $PACKAGES
