# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: yamlfmt_$(latest_version)_Linux_x86_64.tar.gz
artifact_type: tar.gz
binary_name: yamlfmt
github_org: google
github_repo: yamlfmt
