#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"
require_commands fzf make bat awk
install_user_bin fzmake

short_symlink="${RUSH_USER_BIN}/fzm"
rm -f "${short_symlink}"
ln --symbolic "${RUSH_USER_BIN}/fzmake" "${short_symlink}"
install_success
