# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: goose-x86_64-unknown-linux-gnu.tar.gz
artifact_type: tar.gz
binary_name: goose
github_org: aaif-goose
github_repo: goose
