#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

# should match [ref:heroku-install-dir]
HEROKU_INSTALL_DIR="${XDG_DATA_HOME}/rush/pcrockett"

rm -f "${RUSH_USER_BIN}/heroku"
rm -rf "${HEROKU_INSTALL_DIR}/heroku"
rm -rf "${XDG_DATA_HOME}/heroku" # i believe heroku dumps stuff here (plugins etc)

uninstall_success
