#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands docker

latest_version="$(github_latest_tag scandum tintin)"

if [ "$(installed_package_version)" = "${latest_version}" ]; then
  log_attention "Already installed and up-to-date."
  exit
fi

docker build \
  --tag tintin \
  --pull \
  --build-arg "TINTIN_VERSION=${latest_version}" \
  .

install_user_bin tt++
install_success "${latest_version}"
