#!/usr/bin/env bash
set -euo pipefail

# MUD Client
#
# Usage: tt++
#
# Example usage:
#
#     tt++
#
# Dependencies:
#
# - docker
#

init() {
  TINTIN_DOCKER_IMAGE="${TINTIN_DOCKER_IMAGE:-tintin}"
  XDG_STATE_HOME="${XDG_STATE_HOME:-"${HOME}"/.local/state}"
  TINTIN_STATE_DIR="${TINTIN_STATE_DIR:-"${XDG_STATE_HOME}"/tintin}"
  mkdir --parent "${TINTIN_STATE_DIR}"
}

main() {
  init
  docker run --rm -it \
    --volume "${TINTIN_STATE_DIR}:/home/user" \
    --network host \
    "${TINTIN_DOCKER_IMAGE}" \
    tt++ \
    "$@"
  exit $?
}

main "$@"
