#!/usr/bin/env bash
set -Eeuo pipefail

query="$(gum write --placeholder "Question to ask FastGPT (CTRL+D to finish)")"
gpt_command=(kagi gpt "${query}")
gum spin --title "Asking FastGPT..." --show-output "${gpt_command[@]}" \
    | glow
