#!/usr/bin/env bash
set -Eeuo pipefail

export GUM_WRITE_CURSOR_MODE="${GUM_WRITE_CURSOR_MODE:-static}"
export GUM_WRITE_HEIGHT="${GUM_WRITE_HEIGHT:-20}"
export GUM_WRITE_WIDTH="${GUM_WRITE_WIDTH:-90}"

term_width="$(tput cols)"
if [ "${term_width}" -lt "${GUM_WRITE_WIDTH}" ]; then
    GUM_WRITE_WIDTH="${term_width}"
fi

query="$(
    gum write --placeholder "Write something here... (CTRL+D to finish)" \
        --char-limit 0
)"

# let the user see what they wrote after the prompt goes away
printf "> %s\n\n---\n\n" "${query}"

# Kagi FastGPT has started using fancy unicode to denote references, and I don't like how they render at all.
#
# 【1】
#
# replacing those with a couple `sed` commands, so they render like this instead:
#
# \[1]
#
# ...which is proper lint-free markdown
#

gpt_command=(kagi gpt "${query}")
gum spin --title "Waiting for response..." --show-output "${gpt_command[@]}" \
    | sed 's|【|\\[|g' \
    | sed 's|】|]|g' \
    | bat --style rule --wrap never --language md --paging never
