#!/usr/bin/env bash
set -Eeuo pipefail

init() {
    ARCH_WIKI_DIR="/usr/share/doc/arch-wiki/html/en"
    SEARCH_COMMAND="$(declare -f search_wiki)
search_wiki"
}

search_wiki() {
    # shellcheck shell=sh
    # this function isn't executed here in this script directly
    # it's actually a shell function that is dumped into fzf

    # first, search file names. they will always be the first search results.
    rg --files | rg --smart-case --color=always "$@"

    # then search file contents. these results will come after file name results.
    rg --hidden --files-with-matches --color=always --smart-case "$@"
}

exec_fzf() {
    SHELL="sh" FZF_DEFAULT_COMMAND="${SEARCH_COMMAND} ''" fzf "${@}"
}

main() {
    init
    cd "${ARCH_WIKI_DIR}"
    exec_fzf --ansi \
        --disabled \
        --query "" \
        --preview "w3m -cols \$FZF_PREVIEW_COLUMNS {}" \
        --preview-window "up,70%" \
        --bind "enter:become(w3m {})" \
        --bind "change:reload(${SEARCH_COMMAND} {q} || true;)"
}

main
