#!/usr/bin/env bash
set -Eeuo pipefail

init() {
    ARCH_WIKI_DIR="/usr/share/doc/arch-wiki/html/en"
    RG_PREFIX="rg --hidden --files-with-matches --color=always --smart-case "
}

exec_fzf() {
    SHELL="sh" FZF_DEFAULT_COMMAND="${RG_PREFIX} ''" fzf "${@}"
}

main() {
    init
    cd "${ARCH_WIKI_DIR}"
    exec_fzf --ansi \
        --disabled \
        --query "" \
        --preview "w3m -cols \$FZF_PREVIEW_COLUMNS {}" \
        --preview-window "up,70%" \
        --bind "enter:become(w3m {})" \
        --bind "change:reload(${RG_PREFIX} {q} || true;)"
}

main
