#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands unzip

# shellcheck disable=SC2034  # variables used in `install_from_github()`
{
  GITHUB_ORG="dimo414"
  GITHUB_REPO="bkt"
}
BIN_NAME="bkt"

latest_version() {
  echo "v${GITHUB_LATEST_TAG}"
}

installed_version() {
  if ! command_exists "${BIN_NAME}"; then
    echo ""
    return 0
  fi

  installed_package_version
}

artifact_name() {
  echo "bkt.$(latest_version).x86_64-unknown-linux-musl.zip"
}

download_url() {
  echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
  unzip "${ARTIFACT_PATH}"
  install_user_bin "${BIN_NAME}"
}

install_from_github
install_success "$(latest_version)"
