services:
  db:
    image: docker.io/library/postgres:16-alpine
    ports:
      - "127.0.0.1:${PGPORT}:5432"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_DB: "${PGDATABASE}"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data_db:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"

volumes:
  data_db: {}
