# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  db:
    image: docker.io/library/postgres:16-alpine
    ports:
      - "127.0.0.1:${PGPORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_DB: "${PGDATABASE:-postgres}"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data_db:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"

volumes:
  data_db: {}
