#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

src="compose.yaml"
dst="${USER_CWD}/compose.yaml"

if [ -e "${dst}" ] && ! force_please; then
  panic "Already exists: ${dst}"
else
  cp "${src}" "${dst}"
  log_attention "Created ${dst}"
fi
