#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands git

ASDF_DIR="${ASDF_DIR:-"${HOME}/.asdf"}"

test ! -d "${ASDF_DIR}" || panic "asdf is already installed!"

git config --global advice.detachedHead false

latest_tag="$(github_latest_tag asdf-vm asdf)"
git clone https://github.com/asdf-vm/asdf.git "${ASDF_DIR}" --branch "${latest_tag}" --depth 1

# shellcheck disable=SC2016
echo '. "${ASDF_DIR}/asdf.sh"' >> "${HOME}/.profile"

# shellcheck disable=SC2016
echo '. "${ASDF_DIR}/asdf.sh"' >> "${HOME}/.bashrc"
