# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: pandoc-$(latest_version)-linux-amd64.tar.gz
artifact_type: tar.gz
binary_name: pandoc
github_org: jgm
github_repo: pandoc
