#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

# thanks to the GitHub tab in <https://buf.build/docs/cli/installation/>

GITHUB_ORG="bufbuild"
GITHUB_REPO="buf"
BIN_NAME="buf"

latest_version() {
    # strip the leading `v` from the tag name
    echo "${GITHUB_LATEST_TAG}" | cut --characters 2-
}

installed_version() {
    if ! command_exists "${BIN_NAME}"; then
        echo ""
        return 0
    fi

    if ! [[ "$("${BIN_NAME}" --version)" =~ ^([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+)$ ]]; then
        panic "Unable to determine currently installed version!"
        exit 1  # redundant, but useful to shellcheck
    fi

    echo "${BASH_REMATCH[1]}"
}

artifact_name() {
    echo "buf-$(uname -s)-$(uname -m)"
}

download_url() {
    echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
    chmod +x "${ARTIFACT_PATH}"
    mv "${ARTIFACT_PATH}" "${BIN_NAME}"
    install_user_bin "${BIN_NAME}"
}

install_from_github
install_success
