# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: mise-${GITHUB_LATEST_TAG}-linux-x64
artifact_type: raw_binary
binary_name: mise
github_org: jdx
github_repo: mise
