# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: kata-static-$(latest_version)-amd64.tar.zst
artifact_type: tar.gz
binary_name: kata-runtime
github_org: kata-containers
github_repo: kata-containers
