# Copy / paste / modified from <https://github.com/actions/starter-workflows/blob/main/.github/dependabot.yml>
# MIT license
# Dependabot docs: <https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates>

version: 2
updates:
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   commit-message:
  #     prefix: "chore"
  #   schedule:
  #     interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
