# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: cloud-sql-proxy.linux.amd64
artifact_type: raw_binary
binary_name: cloud-sql-proxy
github_org: GoogleCloudPlatform
github_repo: cloud-sql-proxy
