#!/usr/bin/env bash
set -Eeuo pipefail

panic() {
    echo "FATAL: ${*}" >&2
    exit 1
}

expand_globs() {
    # expand glob patterns coming from stdin, write expanded files to stdout
    while read -r line; do
        compgen -G "${line}" || panic "Pattern \`${line}\` does not match anything."
    done
}

expand_globs < lint-scripts \
    | xargs shellcheck

echo "lint: no errors"
