#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
    local script_name
    script_name="$(basename "${1}")"
    echo "Initialize a new package"
    echo
    echo "Usage:"
    echo "  ${script_name} PACKAGE_NAME"
    echo
}

panic() {
    echo "FATAL: ${*}" >&2
    exit 1
}

main() {
    command -v copier &>/dev/null || panic "Must install copier first."

    local PACKAGE_NAME="${1:-}"
    if [ "${PACKAGE_NAME}" == "" ]; then
        usage "${0}"
        panic "Must specify package name."
    fi

    test ! -d "${PACKAGE_NAME}" || panic "${PACKAGE_NAME} already exists!"

    copier copy _templates/github-release "${PACKAGE_NAME}" --trust
}

main "${@}"
