#!/usr/bin/env bash
set -Eeuo pipefail

is_installed() {
    command -v "${1}" &> /dev/null
}

spinner() {
    if is_installed gum; then
        gum spin --title "" --show-output -- "${@}"
    else
        "${@}"
    fi
}

curl_download() {
    local url="${1}"
    local curl_cmd=(
        curl --silent --show-error --fail
        --location "${url}"
    )
    spinner "${curl_cmd[@]}"
}

format_output() {
    if is_installed jq; then
        jq '
            {
                ip,
                city: (.city + ", " + .country),
                coords: ((.latitude | tostring) + ", " + (.longitude | tostring)),
                isp: .organization,
                is_mullvad: .mullvad_exit_ip,
                blacklisted: .blacklisted.blacklisted
            }
        '
    elif is_installed fx; then
        # shellcheck disable=2016  # don't want expressions to expand in single quotes
        fx 'x => `
ip:          ${x.ip}
city:        ${x.city}, ${x.country}
coords:      ${x.latitude}, ${x.longitude}
isp:         ${x.organization}
is_mullvad:  ${x.mullvad_exit_ip}
blacklisted: ${x.blacklisted?.blacklisted}
`'
    elif is_installed bat; then
        bat --language json --style snip
    else
        cat
    fi
}

main() {
    curl_download "https://am.i.mullvad.net/json" \
        | format_output
}

main
