#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

test -d "${USER_CWD}/.git" || git init "${USER_CWD}"

packages_to_run=(
  asdfignore
  editorconfig
  envrc
  ghboilerplate
  gpl
  pre-commit-config
  shellcheckrc
  yamlfmt-config
  yamllint-config
)

rush_cmd=(rush get)

if force_please; then
  rush_cmd+=(--force)
fi

for package in "${packages_to_run[@]}"; do
  "${rush_cmd[@]}" "${package}"
done

test ! -f "${USER_CWD}/.envrc.example" && mv "${USER_CWD}/.envrc" "${USER_CWD}/.envrc.example"
