#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

src_dir="template_dir"
dst_dir="${USER_CWD}/.github"

# TODO: use the following command to help fill in CODEOWNERS automatically:
#
#     gh auth status --active --json hosts --jq '.hosts."github.com"[0].login'
#

if [ -d "${dst_dir}" ]; then
  if force_please; then
    cp --recursive "${src_dir}/"* "${dst_dir}"
    log_attention "Updated ${dst_dir}"
  else
    panic "Already exists: ${dst_dir}. Add --force if you want to update."
  fi
else
  cp --recursive "${src_dir}" "${dst_dir}"
  log_attention "Created ${dst_dir}"
fi
