#!/usr/bin/env bash

#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

dest="${USER_CWD}/template.service"

if [ ! -e "${dest}" ] || force_please; then
  cp template.service "${dest}"
  echo "Generated template at ${dest}"
else
  panic "template.service already exists in this directory. Use --force to overwrite."
fi
