#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands restic

GITHUB_ORG="pcrockett"
GITHUB_REPO="backup"
BIN_NAME="backup"

latest_version() {
    # strip the leading `v` from the tag name
    echo "${GITHUB_LATEST_TAG}" | cut --characters 2-
}

installed_version() {
    if [ ! -x "${RUSH_GLOBAL_BIN}/${BIN_NAME}" ]; then
        echo ""
        return 0
    fi

    if ! [[ "$("${RUSH_GLOBAL_BIN}/${BIN_NAME}" --version)" =~ ^([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+) ]]; then
        panic "Unable to determine currently installed version!"
        exit 1  # redundant, but useful to shellcheck
    fi

    echo "${BASH_REMATCH[1]}"
}

artifact_name() {
    echo "backup"
}

download_url() {
    echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
    install_global_bin "${ARTIFACT_PATH}"
}

install_from_github
install_success
