#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands notify-send sudo

installed_path="${RUSH_GLOBAL_BIN}/notify-send-user"

if files_are_same "${installed_path}" notify-send-user; then
  log_attention "Already installed and up-to-date."
else
  install_global_bin notify-send-user
  install_success
fi
