#!/usr/bin/env bash
set -euo pipefail

# <https://theprivacygroup.com/articles/gdpr-countries/>

get_awk_program() {
    cat <<'EOF'
BEGIN {
    countries["Austria"] = 1;
    countries["Belgium"] = 1;
    countries["Bulgaria"] = 1;
    countries["Croatia"] = 1;
    countries["Cyprus"] = 1;
    countries["Czech"] = 1;
    countries["Denmark"] = 1;
    countries["Estonia"] = 1;
    countries["Finland"] = 1;
    countries["France"] = 1;
    countries["Germany"] = 1;
    countries["Greece"] = 1;
    countries["Hungary"] = 1;
    countries["Ireland"] = 1;
    countries["Italy"] = 1;
    countries["Latvia"] = 1;
    countries["Lithuania"] = 1;
    countries["Luxembourg"] = 1;
    countries["Malta"] = 1;
    countries["Netherlands"] = 1;
    countries["Poland"] = 1;
    countries["Portugal"] = 1;
    countries["Romania"] = 1;
    countries["Slovakia"] = 1;
    countries["Slovenia"] = 1;
    countries["Spain"] = 1;
    countries["Sweden"] = 1;
    countries["Switzerland"] = 1;
    countries["Iceland"] = 1;
    countries["Lichtenstein"] = 1;
    countries["Norway"] = 1;
}
$3 in countries { print $1 }
EOF
}

random_exit_ip() {
    tailscale exit-node list \
        | grep --invert-match --perl-regexp '^#' \
        | grep --invert-match --perl-regexp '^\s*$' \
        | tail --lines +2 \
        | awk "$(get_awk_program)" \
        | shuf --head-count 1
}

main() {
    local exit_node
    exit_node="$(random_exit_ip)"
    if [ "${exit_node}" == "" ]; then
        exit 1 # `tailscale` has already printed a good error to stderr, no need to repeat it
    fi
    tailscale set --exit-node "${exit_node}"
}

main
