#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands tar

# shellcheck disable=SC2034  # variables used in `install_from_github()`
{
  GITHUB_ORG="wezm"
  GITHUB_REPO="rsspls"
}
BIN_NAME="rsspls"

latest_version() {
  echo "${GITHUB_LATEST_TAG}"
}

installed_version() {
  if ! command_exists "${BIN_NAME}"; then
    echo ""
    return 0
  fi

  if ! [[ "$("${BIN_NAME}" --version)" =~ ^rsspls\ version\ ([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+) ]]; then
    panic "Unable to determine currently installed version!"
    exit 1 # redundant, but useful to shellcheck
  fi

  echo "${BASH_REMATCH[1]}"
}

artifact_name() {
  echo "rsspls-${GITHUB_LATEST_TAG}-x86_64-unknown-linux-musl.tar.gz"
}

download_url() {
  echo "https://releases.wezm.net/rsspls/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
  tar -xzf "$(artifact_name)"
  install_user_bin "${BIN_NAME}"
}

install_from_github
install_success
