# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/script-nushell
description: Grab files from a Git repository
script_name: gitgrab
