#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands tar

GITHUB_ORG="sinclairtarget"
GITHUB_REPO="git-who"
BIN_NAME="git-who"

latest_version() {
    echo "${GITHUB_LATEST_TAG}"
}

installed_version() {
    if ! command_exists "${BIN_NAME}"; then
        echo ""
        return 0
    fi

    if ! [[ "$("${BIN_NAME}" --version)" =~ ^(v[[:digit:]]+\.[[:digit:]]+(\.[[:digit:]]+)*) ]]; then
        panic "Unable to determine currently installed version!"
        exit 1  # redundant, but useful to shellcheck
    fi

    echo "${BASH_REMATCH[1]}"
}

artifact_name() {
    echo "gitwho_${GITHUB_LATEST_TAG}_linux_amd64.tar.gz"
}

download_url() {
    echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
    tar xzf "${ARTIFACT_PATH}"
    install_user_bin "linux_amd64/${BIN_NAME}"
}

install_from_github
install_success
