#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands curl base64
bin_name="caldav-dump"
installed_path="${RUSH_GLOBAL_BIN}/${bin_name}"

if files_are_same "${installed_path}" "${bin_name}"; then
  log_attention "Already installed and up-to-date."
else
  install_global_bin "${bin_name}"
  install_success
fi
