# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/basic
description: Mark all GitHub notifications as "read" where the notification reason is `review_requested` and PR state is `merged`
