#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

# roc is a young project, and currently uses nightly releases without any version
# numbers. later when roc grows up, we can create a proper github package with
# `install_success`. until that day, we update roc manually by running `rush roclang`.

temp_dir="$(mktemp_dir)"
pushd "${temp_dir}" &>/dev/null

on_exit() {
    popd &>/dev/null
    rm -rf "${temp_dir}"
}
trap 'on_exit' EXIT

install_dir="${XDG_DATA_HOME}/roc"

# nightly can be found here:
#
# <https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz>
#
extract_tar_gz_url \
    "https://github.com/roc-lang/roc/releases/download/alpha3-rolling/roc-linux_x86_64-alpha3-rolling.tar.gz" \
    "${install_dir}" \
    --strip-components 1

ln --symbolic --force "${install_dir}/roc" "${RUSH_USER_BIN}"
ln --symbolic --force "${install_dir}/roc_language_server" "${RUSH_USER_BIN}"
