#!/usr/bin/env bash
set -Eeuo pipefail

# wrap `git blame` so that it will automatically run with the parameters:
#
#     --ignore-revs-file .git-blame-ignore-revs
#
# but ONLY if the `.git-blame-ignore-revs` file actually exists.

DEFAULT_IGNORE_REVS_FILE=".git-blame-ignore-revs"

init() {
  # thanks <https://stackoverflow.com/a/957978/138757>
  REPO_ROOT="$(git rev-parse --show-toplevel)"
}

main() {
  init

  local full_path="${REPO_ROOT}/${DEFAULT_IGNORE_REVS_FILE}"
  local command=(git blame)
  if [ -f "${full_path}" ]; then
    command+=(--ignore-revs-file "${full_path}")
  fi
  command+=("${@}")
  "${command[@]}"
}

main "${@}"
