# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: delta-$(latest_version)-x86_64-unknown-linux-musl.tar.gz
artifact_type: tar.gz
binary_name: delta
github_org: dandavison
github_repo: delta
