#!/usr/bin/env bash
# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

GITHUB_ORG="simplex-chat"
GITHUB_REPO="simplex-chat"
BIN_NAME="simplex-chat"

latest_version() {
    echo "${GITHUB_LATEST_TAG}"
}

installed_version() {
    if ! command_exists "${BIN_NAME}"; then
        echo ""
        return 0
    fi

    if ! [[ "$("${BIN_NAME}" --version)" =~ ^SimpleX\ Chat\ (v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+) ]]; then
        panic "Unable to determine currently installed version!"
        exit 1  # redundant, but useful to shellcheck
    fi

    echo "${BASH_REMATCH[1]}"
}

artifact_name() {
    echo "simplex-chat-ubuntu-22_04-x86_64"
}

download_url() {
    echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
    mv "${ARTIFACT_PATH}" "${BIN_NAME}"
    chmod +x "${BIN_NAME}"
    install_user_bin "${BIN_NAME}"
}

install_from_github
install_success
