#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands curl zcat

# inspired by <https://install.duckdb.org/>
OS=$(uname -s)
ARCH=$(uname -m)
LATEST_VERSION="$(curl_download https://duckdb.org/data/latest_stable_version.txt)"

if [ "${LATEST_VERSION}" = "$(installed_package_version)" ]; then
  log_attention "Already installed and up-to-date."
  exit 0
fi

DIST=

if [ "${OS}" = "Linux" ]; then
  if [ "${ARCH}" = "x86_64" ] || [ "${ARCH}" = "amd64" ]; then
    DIST=linux-amd64
  elif [ "${ARCH}" = "aarch64" ] || [ "${ARCH}" = "arm64" ]; then
    DIST=linux-arm64
  fi
elif [ "${OS}" = "Darwin" ]; then
  if [ "${ARCH}" = "x86_64" ]; then
    DIST=osx-amd64
  elif [ "${ARCH}" = "arm64" ]; then
    DIST=osx-arm64
  fi
fi

if [ -z "${DIST}" ]; then
  echo "Operating system '${OS}' / architecture '${ARCH}' is unsupported." 1>&2
  exit 1
fi

temp_dir="$(mktemp_dir)"
cleanup() {
  local exit_code="${?}"
  popd &>/dev/null || panic "unable to cd away from ${temp_dir}"
  rm -rf "${temp_dir}"
  return "${exit_code}"
}
trap 'cleanup' EXIT
pushd "${temp_dir}" &>/dev/null

URL="https://install.duckdb.org/v${LATEST_VERSION}/duckdb_cli-${DIST}.gz"
curl_download "${URL}" >duckdb.gz
zcat <duckdb.gz >duckdb
chmod +x duckdb
install_user_bin duckdb
install_success "${LATEST_VERSION}"
