#!/usr/bin/env bash

# steps to uninstall are just the reverse of what we find in https://tailscale.com/install.sh

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"
as_root systemctl stop tailscaled
as_root apt-get purge --yes tailscale tailscale-archive-keyring
as_root rm -f /usr/share/keyrings/tailscale-archive-keyring.gpg
as_root rm -f /etc/apt/sources.list.d/tailscale.list
