#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

dest_file="${USER_CWD}/.yamllint.yml"

if [ ! -f "${dest_file}" ] || force_please; then
  cp yamllint-template.yml "${dest_file}"
else
  panic ".yamllint.yml already exists in this directory. Use --force to overwrite."
fi
