#!/usr/bin/env bash
set -Eeuo pipefail

# https://cloud.google.com/sdk/docs/downloads-docker
#
# a wrapper script for the gcloud docker container. makes the container behave as if you
# have the CLI installed traditionally.
#
# usage:
#
#   gcloud help
#

init() {
  XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"${HOME}/.config"}"
  PCROCKETT_GCLOUD_CONFIG_DIR="${PCROCKETT_GCLOUD_CONFIG_DIR:-"${XDG_CONFIG_HOME}/gcloud"}"
  mkdir --parent "${PCROCKETT_GCLOUD_CONFIG_DIR}"

  # as of this writing, this script is called `gcloud`. however there should also be a
  # symlink to this script called `docker-credential-gcloud`. we use the script name to
  # figure out what command to actually pass to the container.
  CONTAINER_COMMAND="$(basename "$0")"
}

main() {
  init

  docker_cmd=(
    docker run --rm
    --user "$(id --user):$(id --group)"
    --volume "${PCROCKETT_GCLOUD_CONFIG_DIR}:/home/cloudsdk/.config/gcloud"
    --volume "${PWD}:/tmp/workdir"
    --workdir "/tmp/workdir"
    --env TERM="${TERM}"
    --interactive
  )

  if [ -d "${HOME}/.docker" ]; then
    docker_cmd+=(--volume "${HOME}/.docker:/home/cloudsdk/.docker")
  fi

  if tty --quiet; then
    docker_cmd+=(--tty)
  fi

  # get all CLOUDSDK_* environment variables and feed them into the docker command
  while IFS= read -r var_setting || [ -n "${var_setting}" ]; do
    docker_cmd+=(--env "${var_setting}")
  done < <(env | grep --perl-regexp "^CLOUDSDK_")

  docker_cmd+=(
    localhost/gcloud "${CONTAINER_COMMAND}" "${@}"
  )

  if [ "${PCROCKETT_GCLOUD_DEBUG:-}" != "" ]; then
    cat >&2 <<EOF
Running...

  ${docker_cmd[*]}

EOF
  fi

  "${docker_cmd[@]}"
}

main "$@"
