#!/usr/bin/env bash
set -Eeuo pipefail

# https://cloud.google.com/sdk/docs/downloads-docker
#
# a wrapper script for the gcloud docker container. makes the container behave as if you have the
# CLI installed traditionally.
#
# usage:
#
#     gcloud help
#

config_home="${XDG_CONFIG_HOME:-"${HOME}/.config"}"

docker_cmd=(
    docker run --rm --interactive --tty
        --user "$(id --user):$(id --group)"
        --volume "${config_home}/gcloud:/home/cloudsdk/.config/gcloud"
        --env TERM="${TERM}"
)

# get all CLOUDSDK_* environment variables and feed them into the docker command
while IFS= read -r var_setting || [ -n "${var_setting}" ]; do
    docker_cmd+=(--env "${var_setting}")
done < <(env | grep --perl-regexp "^CLOUDSDK_")

docker_cmd+=(
    localhost/gcloud gcloud "${@}"
)

"${docker_cmd[@]}"
