#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"
rm -f "${RUSH_USER_BIN}/gcloud" "${RUSH_USER_BIN}/docker-credential-gcloud"
docker image rm localhost/gcloud
uninstall_success
