# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/script
description: Render mermaid diagrams in your terminal
script_name: merminate
