#!/usr/bin/env -S deno run --allow-read

import { renderMermaidAscii } from "npm:beautiful-mermaid@0.1.3";
import * as io from "jsr:@std/io@0.225.3";

async function main() {
  try {
    const rawInput = await io.readAll(Deno.stdin);
    const decoder = new TextDecoder("utf-8");
    const unicodeInput = decoder.decode(rawInput);
    const diagram = renderMermaidAscii(unicodeInput);
    console.log(diagram);
  } catch (error) {
    console.error("Error rendering mermaid:", error);
    Deno.exit(1);
  }
}

await main();
