#!/usr/bin/env bash
set -euo pipefail

# like xdg-open, but discarding output and disowning the process
#
# Usage: bgopen [ITEMS...]
#
# Example usage:
#
#     # open one or more files with interactive fzf file picker
#     bgopen
#
#     # open a single file
#     bgopen some-file.pdf
#
#     # open multiple URLs in your browser
#     bgopen https://philcrockett.com/ http://kagi.com/
#
# Environment variables:
#
# * BGOPEN_HEIGHT: height of interactive UI (defaults to 20)
#
# Dependencies:
#
# * bgstart (also in this rush-repo)
# * xdg-open
# * fzf (optional)
#

fzf_ui() {
  fzf --multi --height "${BGOPEN_HEIGHT:-20}" --reverse --prompt 'Select file(s): ' --print0
}

main() {
  if [ $# -eq 0 ]; then
    fzf_ui | xargs -0 -L 1 bgstart xdg-open
  else
    for arg in "$@"; do
      bgstart xdg-open "$arg"
    done
  fi
  exit
}

main "$@"
