#!/usr/bin/env bash
set -euo pipefail

# like xdg-open, but discarding output and disowning the process
#
# Usage: bgopen [XDG_OPEN_ARGS...]
#
# Example usage:
#
#     bgopen some-file.pdf
#
# Dependencies:
#
# * xdg-open
#

main() {
  bgstart xdg-open "$@"
  exit
}

main "$@"
