#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

systemctl disable --now --user filen-sync.service

config_dir="${XDG_CONFIG_HOME}/systemd/user"
rm -f "${config_dir}/filen-sync.service" "${config_dir}/filen-sync.timer"
systemctl daemon-reload --user
