name: CI

on:
  push:
    branches: [ $default-branch ]
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ $default-branch ]
  # schedule:
  #   - cron: "17 3 * * 1"  # every Monday at 03:17 UTC   https://crontab.guru/#17_3_*_*_1

permissions:
  contents: read
  # packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: ["3.10", "3.11", "3.12"]

    # steps:

    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # - uses: actions/checkout@v3
    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: ${{ matrix.python-version }}

    # - name: Install Dependencies
    #   run: |
    #     poetry install --no-interaction --no-root

    # - name: Run Tests
    #   run: |
    #     pytest
