# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches: [main]
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: ["**"]

  # schedule:
  #   - cron: "17 3 * * 1"  # every Monday at 03:17 UTC   https://crontab.guru/#17_3_*_*_1

permissions:
  contents: read
  # packages: write

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - uses: pcrockett/setup-just@bfd0f2be2991d96e39d8d4c3bba4018d44857339  # v0.1.0
      - uses: pcrockett/setup-shfmt@d8d8c3e8826447cc32357cd9436c6b90d1a01aa3  # v0.1.0
      - uses: pcrockett/setup-yamlfmt@2949e59bb1f6d24f519d0dfa2560a0dbcd563fcc  # v0.1.1
      - uses: pcrockett/setup-pre-commit@19ef06ee4c041b82a9ad48337154bd4429158560  # v0.1.0
      - uses: pcrockett/setup-actionlint@df8241ffe42b97e7324773d54523a29a59e7d485  # v0.1.0

      - run: just lint

  build:
    runs-on: ubuntu-latest

    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
    #   with:
    #     python-version: ${{ matrix.python-version }}

    # - name: Install Dependencies
    #   run: |
    #     poetry install --no-interaction --no-root
