# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches: [main]
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: ["**"]

  # schedule:
  #   - cron: "17 3 * * 1"  # every Monday at 03:17 UTC   https://crontab.guru/#17_3_*_*_1

permissions:
  contents: read
  # packages: write

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-hooks|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea  # v4.2.1
      - run: just lint

  build:
    runs-on: ubuntu-latest

    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
    #   with:
    #     python-version: ${{ matrix.python-version }}

    # - name: Install Dependencies
    #   run: |
    #     poetry install --no-interaction --no-root
