# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches: [ main ]
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "**" ]
  # schedule:
  #   - cron: "17 3 * * 1"  # every Monday at 03:17 UTC   https://crontab.guru/#17_3_*_*_1

permissions:
  contents: read
  # packages: write

jobs:

  pre-commit:
    name: "pre-commit"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5  # for pre-commit
      - name: pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all --show-diff-on-failure --color=always

  build:

    runs-on: ubuntu-latest

    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # - name: Set up Python ${{ matrix.python-version }}
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: ${{ matrix.python-version }}

    # - name: Install Dependencies
    #   run: |
    #     poetry install --no-interaction --no-root

    # - name: Run Tests
    #   run: |
    #     pytest

    # - uses: earthly/actions-setup@v1
    #   with:
    #     version: ^0.8.0

    # - name: Lint / Test / Build
    #   run: earthly --ci +all
