name: Release

on: workflow_dispatch

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # - uses: earthly/actions-setup@v1
    #   with:
    #     version: ^0.8.0

    # - name: Install fx
    #   run: |
    #     curl -SsfL https://philcrockett.com/yolo/v1.sh \
    #       | bash -s -- fx

    # - name: Release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: ./scripts/release.sh
