#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

# shellcheck disable=SC2034  # variables used in `install_from_github()`
{
  GITHUB_ORG="astral-sh"
  GITHUB_REPO="uv"
}
BIN_NAME="uv"

latest_version() {
  echo "${GITHUB_LATEST_TAG}"
  # strip the leading `v` from the tag name:
  # echo "${GITHUB_LATEST_TAG}" | cut --characters 2-
}

installed_version() {
  if ! command_exists "${BIN_NAME}"; then
    echo ""
    return 0
  fi

  installed_package_version
}

artifact_name() {
  echo "uv-installer.sh"
}

download_url() {
  echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
  chmod +x "${ARTIFACT_PATH}"
  UV_NO_MODIFY_PATH=1 "${ARTIFACT_PATH}"
}

install_from_github
install_success "$(latest_version)"
