#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands tar java

# shellcheck disable=SC2034  # variables used in `install_from_github()`
{
  GITHUB_ORG="AsamK"
  GITHUB_REPO="signal-cli"
}
BIN_NAME="signal-cli"

latest_version() {
  # strip the leading `v` from the tag name:
  echo "${GITHUB_LATEST_TAG}" | cut --characters 2-
}

installed_version() {
  if ! command_exists "${BIN_NAME}"; then
    echo ""
    return 0
  fi

  installed_package_version
}

artifact_name() {
  echo "signal-cli-$(latest_version).tar.gz"
}

download_url() {
  echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
  tar -xzf "${ARTIFACT_PATH}"
  local extracted_dir
  extracted_dir="$(basename "${ARTIFACT_PATH}" .tar.gz)"
  local install_dir="${XDG_DATA_HOME}/signal-cli"
  local config_file="${XDG_CONFIG_HOME}/signal-cli/config.json"

  if [ ! -f "${config_file}" ]; then
    # signal-cli's default data location is bundled with all the static assets. create
    # a default config file that places data in another directory so we don't blow away
    # all our data on every new release.
    local signal_cli_data_dir="${XDG_DATA_HOME}/signal-cli-data"
    mkdir --parent "${signal_cli_data_dir}"
    cat >"${config_file}" <<EOF
{
  "dataDir": "${signal_cli_data_dir}"
}
EOF
  fi

  rm -rf "${install_dir}.old"
  test ! -d "${install_dir}" || mv "${install_dir}" "${install_dir}.old"
  mv "${extracted_dir}" "${install_dir}"
  ln --symbolic --force "${install_dir}/bin/signal-cli" "${RUSH_USER_BIN}/signal-cli"
}

install_from_github
install_success "$(latest_version)"
