#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

GITHUB_ORG="stepchowfun"
GITHUB_REPO="tagref"
BIN_NAME="tagref"

latest_version() {
  echo "${GITHUB_LATEST_TAG}"
}

installed_version() {
  if ! command_exists "${BIN_NAME}"; then
    echo ""
    return 0
  fi

  installed_package_version
}

artifact_name() {
  echo "tagref-x86_64-unknown-linux-gnu"
}

download_url() {
  echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
  chmod +x "${ARTIFACT_PATH}"
  mv "${ARTIFACT_PATH}" "${BIN_NAME}"
  install_user_bin "${BIN_NAME}"
}

install_from_github
install_success "$(latest_version)"
