name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false
      - uses: pcrockett/setup-yamlfmt@2949e59bb1f6d24f519d0dfa2560a0dbcd563fcc  # v0.1.1
      - uses: pcrockett/setup-bats@b791173505d0a1947d46793e9aae33a962cfd949  # v0.1.0
      - uses: pcrockett/setup-just@bfd0f2be2991d96e39d8d4c3bba4018d44857339  # v0.1.0
      - name: Install tools
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -SsfL http://philcrockett.com/yolo/v1.sh \
            | bash -s -- tagref asdf rush
          asdf plugin add shfmt "https://github.com/pcrockett/asdf-shfmt.git"
          asdf install
          echo "${HOME}/.asdf/shims" >> "${GITHUB_PATH}"

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0

      # borrowed /modified the following from <https://github.com/pre-commit/action/blob/main/action.yml>
      - run: python -m pip install pre-commit
      - run: python -m pip freeze --local
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: just all
