#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands rg tar

# shellcheck disable=SC2034  # variables used in `install_from_github()`
{
    GITHUB_ORG="acheronfail"
    GITHUB_REPO="repgrep"
}
BIN_NAME="rgr"

latest_version() {
    echo "${GITHUB_LATEST_TAG}"
}

installed_version() {
    if ! command_exists "${BIN_NAME}"; then
        echo ""
        return 0
    fi

    installed_package_version
}

artifact_name() {
    echo "repgrep-$(latest_version)-x86_64-unknown-linux-musl.tar.gz"
}

download_url() {
    echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/${GITHUB_LATEST_TAG}/$(artifact_name)"
}

install_artifact() {
    tar -xzf "${ARTIFACT_PATH}"
    subdir="$(basename "${ARTIFACT_PATH}" .tar.gz)"
    install_user_bin "${subdir}/${BIN_NAME}"
}

install_from_github
install_success "$(latest_version)"
