# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: Nextcloud-$(latest_version)-x86_64.AppImage
artifact_type: raw_binary
binary_name: Nextcloud.AppImage
github_org: nextcloud-releases
github_repo: desktop
