# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: jira_$(latest_version)_linux_x86_64.tar.gz
artifact_type: tar.gz
binary_name: jira
github_org: ankitpokhrel
github_repo: jira-cli
