# Changes here will be overwritten by Copier
# Don't edit manually!
# <https://copier.readthedocs.io/en/stable/updating/>
_src_path: _templates/github-release
artifact_name: age-plugin-yubikey-$(latest_version)-x86_64-linux.tar.gz
artifact_type: tar.gz
binary_name: age-plugin-yubikey
github_org: str4d
github_repo: age-plugin-yubikey
