#!/usr/bin/env bash

# shellcheck source=lib.sh
source "${REPO_PATH}/lib.sh"

require_commands tar

# shellcheck disable=SC2034  # variables used in `install_from_github()`
{
  GITHUB_ORG="str4d"
  GITHUB_REPO="age-plugin-yubikey"
}
BIN_NAME="age-plugin-yubikey"

latest_version() {
  if [ "${GITHUB_LATEST_TAG}" == "v0.5.1" ]; then
    # this release is broken for linux, see <https://github.com/str4d/age-plugin-yubikey/issues/225>
    # just fall back to previous release
    echo "v0.5.0"
  else
    echo "${GITHUB_LATEST_TAG}"
  fi
}

installed_version() {
  if ! command_exists "${BIN_NAME}"; then
    echo ""
    return 0
  fi

  installed_package_version
}

artifact_name() {
  echo "age-plugin-yubikey-$(latest_version)-x86_64-linux.tar.gz"
}

download_url() {
  echo "https://github.com/${GITHUB_ORG}/${GITHUB_REPO}/releases/download/$(latest_version)/$(artifact_name)"
}

install_artifact() {
  tar -xzf "${ARTIFACT_PATH}"
  install_user_bin "age-plugin-yubikey/${BIN_NAME}"
}

install_from_github
install_success "$(latest_version)"
